#!/bin/bash
if [ -e /etc/environment ] ; then
   echo "sourcing /etc/environment"
   source /etc/environment
fi
SCRIPTPATH=$(dirname "$0")
cd "$SCRIPTPATH"
if [ ! -e cpanfile.snapshot ] ; then
    carton install
fi
carton exec client/dpp.pl "$@"
